export const DATA = [
  {
    id: 1,
    name: 'Vinay',
    phone: 98765424,
    email: 'shwetali98@gmail.com',
    language: 'java',
    address: '36/A, Ajanta complex, Near KEM Hosp, Maharashtra 401200',
    status: 'Bench( 01jan to 20 Dec',
    target: 5,
    Technology: 'Business Analyst',
    Experience: '1 year & 0 months',
    CV: '1 year & 0 months',
    ClientName: 'Linkin Time',
    EndDate: '31 December 2020',
    PrimaryResource: '10',
    SecondaryResource: '14',
    URL: 'https://social.nimapinfotech.com/group/dotnet-developers',
    title: 'Digital Agency',
    description:
      'I’m designing adocument and don’t want to get bogged down in what the text actually say',
    StartDate: '10/December/2020',
    orderno: '014914',
    status: 'Bench (01 Jan 2020 to 11 Nov 2020)',
  },

  {
    id: 2,
    name: 'Haroon',
    phone: 98765424,
    email: 'shwetali98@gmail.com',
    language: 'java',
    address: '36/A, Ajanta complex, Near KEM Hosp, Maharashtra 401200',
    status: 'Bench( 01jan to 20 Dec',
    target: 5,
    Technology: 'Business Analyst',
    Experience: '1 year & 0 months',
    CV: '1 year & 0 months',
    ClientName: 'Linkin Time',
    EndDate: '31 December 2020',
    PrimaryResource: '10',
    SecondaryResource: '14',
    URL: 'https://social.nimapinfotech.com/group/dotnet-developers',
    title: 'Digital Agency',
    description:
      'I’m designing adocument and don’t want to get bogged down in what the text actually say',
    StartDate: '10/December/2020',
    orderno: '014914',
    status: ' Bench (01 Jan 2020 to 11 Nov 2020)',
  },
];
